---
general:
  buildTool: "mta"

stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true

  Additional Unit Tests:
    npmExecuteScripts: false
    karmaExecuteTests: false

  Acceptance:
    cloudFoundryDeploy: false
    cfApiEndpoint: "https://api.cf.us10.hana.ondemand.com"
    cfOrg: "f777886dtrial"
    cfSpace: "dev"
    cfAppName: "mad"
    cfCredentialsId: "cf-deploy-basic"
    uiVeri5ExecuteTests: false

  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10.hana.ondemand.com"
    cfOrg: "f777886dtrial"
    cfSpace: "dev"
    cfAppName: "mad"
    cfCredentialsId: "cf-deploy-basic"
    tmsUpload: false

steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"

  npmExecuteLint:
    failOnError: true

  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"

  tmsUpload:
    nodeName: "qa"
    credentialsId: "tms-sk"